### ISSUE TITLE
Does not work in Rails 4.0

### ISSUE THREAD

**Issue by voltechs** [yonbergman/enumify#7]
class Partners::Contact < ActiveRecord::Base
  enum :status, [:pending, :active]
end

rails s
$ h.contacts.first.status
NoMethodError: undefined method `empty?' for 1:Fixnum
    from /Users/volte/a2/vendor/bundle/gems/enumify-0.0.5/lib/enumify/model.rb:11:in`block in enum'
    from (irb):6
